import SwiftUI

/// Feature-level localized keys introduced by the multi-page dashboard. Keeping these in a
/// separate extension lets the core design-system string table stay compact while preserving the
/// app-wide rule that views never render raw user-facing strings.
extension Str {
    static let navigationLabel: LocalizedStringKey = "navigation.label"
    static let navigationOverview: LocalizedStringKey = "navigation.overview"
    static let navigationMarket: LocalizedStringKey = "navigation.market"
    static let navigationCommunity: LocalizedStringKey = "navigation.community"

    static let feedLive: LocalizedStringKey = "feed.live"
    static let feedCached: LocalizedStringKey = "feed.cached"
    static let feedUnavailable: LocalizedStringKey = "feed.unavailable"
    static let feedRetry: LocalizedStringKey = "feed.retry"
    static let feedShowingCached: LocalizedStringKey = "feed.showingCached"
    static let feedLoading: LocalizedStringKey = "feed.loading"
    static let feedWaiting: LocalizedStringKey = "feed.waiting"

    static let statChange30m: LocalizedStringKey = "stat.change30m"
    static let statTodayHigh: LocalizedStringKey = "stat.todayHigh"
    static let statLocalRecord: LocalizedStringKey = "stat.localRecord"
    static let statRangeAverage: LocalizedStringKey = "stat.rangeAverage"
    static let chartAutomatic: LocalizedStringKey = "chart.automatic"
    static let chartResolution: LocalizedStringKey = "chart.resolution"
    static let chartCandleInterval: LocalizedStringKey = "chart.candleInterval"
    static let chartMetricOpenShort: LocalizedStringKey = "chart.metric.open.short"
    static let chartMetricHighShort: LocalizedStringKey = "chart.metric.high.short"
    static let chartMetricLowShort: LocalizedStringKey = "chart.metric.low.short"
    static let chartMetricCloseShort: LocalizedStringKey = "chart.metric.close.short"
    static let chartMetricOpen: LocalizedStringKey = "chart.metric.open"
    static let chartMetricHigh: LocalizedStringKey = "chart.metric.high"
    static let chartMetricLow: LocalizedStringKey = "chart.metric.low"
    static let chartMetricClose: LocalizedStringKey = "chart.metric.close"
    static let chartWindowCoverage: LocalizedStringKey = "chart.windowCoverage"
    static let chartWindowCoverageHelp: LocalizedStringKey = "chart.windowCoverage.help"
    static let chartCandleLatest: LocalizedStringKey = "chart.candle.latest"
    static let chartCandleSelected: LocalizedStringKey = "chart.candle.selected"
    static let chartCandleLoadingTitle: LocalizedStringKey = "chart.candle.loading.title"
    static let chartCandleLoadingSubtitle: LocalizedStringKey = "chart.candle.loading.subtitle"
    static let chartCandleUnavailableTitle: LocalizedStringKey = "chart.candle.unavailable.title"
    static let chartCandleUnavailableSubtitle: LocalizedStringKey = "chart.candle.unavailable.subtitle"
    static let chartCandleGatheringTitle: LocalizedStringKey = "chart.candle.gathering.title"
    static let chartCandleGatheringSubtitle: LocalizedStringKey = "chart.candle.gathering.subtitle"

    static let marketSpot: LocalizedStringKey = "market.spot"
    static let marketTokenSymbol: LocalizedStringKey = "market.tokenSymbol"
    static let marketClose: LocalizedStringKey = "market.close"
    static let marketVolume: LocalizedStringKey = "market.volume"
    static let marketLiquidity: LocalizedStringKey = "market.liquidity"
    static let marketTransactions: LocalizedStringKey = "market.transactions"
    static let marketMarketCap: LocalizedStringKey = "market.marketCap"
    static let marketDataSource: LocalizedStringKey = "market.dataSource"
    static let marketView: LocalizedStringKey = "market.view"
    static let marketTimeframe: LocalizedStringKey = "market.timeframe"
    static let marketQuoteFeed: LocalizedStringKey = "market.feed.quote"
    static let marketChartFeed: LocalizedStringKey = "market.feed.chart"
    static let marketFeedUnavailableDetail: LocalizedStringKey = "market.feed.unavailableDetail"

    static let communityTitle: LocalizedStringKey = "community.title"
    static let communityLatestRelease: LocalizedStringKey = "community.latestRelease"
    static let communityNoReleases: LocalizedStringKey = "community.noReleases"
    static let communityAccounts: LocalizedStringKey = "community.accounts"
    static let communityPlayers: LocalizedStringKey = "community.players"
    static let communityRealm: LocalizedStringKey = "community.realm"
    static let communityRealms: LocalizedStringKey = "community.realms"
    static let communityRealmType: LocalizedStringKey = "community.realmType"
    static let communityLeaderboard: LocalizedStringKey = "community.leaderboard"
    static let communityNoRankings: LocalizedStringKey = "community.noRankings"
    static let communityLoading: LocalizedStringKey = "community.loading"
    static let communityUnavailable: LocalizedStringKey = "community.unavailable"
    static let communityPartial: LocalizedStringKey = "community.partial"
    static let communityViewRelease: LocalizedStringKey = "community.viewRelease"
    static let communityRecentReleases: LocalizedStringKey = "community.recentReleases"

    static let actionPlay: LocalizedStringKey = "action.play"
    static let actionWiki: LocalizedStringKey = "action.wiki"
    static let actionHighScores: LocalizedStringKey = "action.highScores"
    static let actionDiscord: LocalizedStringKey = "action.discord"
    static let actionGitHub: LocalizedStringKey = "action.github"
    static let actionCopyContract: LocalizedStringKey = "action.copyContract"
    static let actionContractCopied: LocalizedStringKey = "action.contractCopied"
    static let actionExportCSV: LocalizedStringKey = "action.exportCSV"
    static let actionExportJSON: LocalizedStringKey = "action.exportJSON"

    static let settingsAppearance: LocalizedStringKey = "settings.appearance"
    static let settingsMenuBar: LocalizedStringKey = "settings.menuBar"
    static let settingsMenuPlayers: LocalizedStringKey = "settings.menu.players"
    static let settingsMenuPlayersChange: LocalizedStringKey = "settings.menu.playersChange"
    static let settingsMenuToken: LocalizedStringKey = "settings.menu.token"
    static let settingsMenuFull: LocalizedStringKey = "settings.menu.full"
    static let settingsNotifications: LocalizedStringKey = "settings.notifications"
    static let settingsNotificationsChecking: LocalizedStringKey = "settings.notifications.checking"
    static let settingsNotificationsAllow: LocalizedStringKey = "settings.notifications.allow"
    static let settingsNotificationsDenied: LocalizedStringKey = "settings.notifications.denied"
    static let settingsNotificationsOpen: LocalizedStringKey = "settings.notifications.open"
    static let settingsNotificationsTest: LocalizedStringKey = "settings.notifications.test"
    static let settingsNotificationsExplanation: LocalizedStringKey =
        "settings.notifications.explanation"
    static let settingsNotificationsRealmCategory: LocalizedStringKey =
        "settings.notifications.category.realm"
    static let settingsNotificationsGameCategory: LocalizedStringKey =
        "settings.notifications.category.game"
    static let settingsNotificationsMarketCategory: LocalizedStringKey =
        "settings.notifications.category.market"
    static let settingsNotificationsDeliveryCategory: LocalizedStringKey =
        "settings.notifications.category.delivery"
    static let settingsNotificationsBlockedAlerts: LocalizedStringKey =
        "settings.notifications.blockedAlerts"
    static let settingsNotificationsTestRequested: LocalizedStringKey =
        "settings.notifications.testRequested"
    static let settingsPopulationAlerts: LocalizedStringKey = "settings.alerts.population"
    static let settingsPopulationAtLeast: LocalizedStringKey = "settings.alerts.populationAtLeast"
    static let settingsReleaseAlerts: LocalizedStringKey = "settings.alerts.releases"
    static let settingsCooldown: LocalizedStringKey = "settings.alerts.cooldown"
    static let settingsCooldownOff: LocalizedStringKey = "settings.alerts.cooldown.off"
    static let settingsCooldown15m: LocalizedStringKey = "settings.alerts.cooldown.15m"
    static let settingsCooldown1h: LocalizedStringKey = "settings.alerts.cooldown.1h"
    static let settingsCooldown4h: LocalizedStringKey = "settings.alerts.cooldown.4h"
    static let settingsCooldown1d: LocalizedStringKey = "settings.alerts.cooldown.1d"
    static let settingsQuietHours: LocalizedStringKey = "settings.alerts.quietHours"
    static let settingsQuietFrom: LocalizedStringKey = "settings.alerts.quietFrom"
    static let settingsQuietTo: LocalizedStringKey = "settings.alerts.quietTo"
    static let settingsRollingWindow: LocalizedStringKey = "settings.alerts.rollingWindow"
    static let settingsGainAlerts: LocalizedStringKey = "settings.alerts.gains"
    static let settingsLossAlerts: LocalizedStringKey = "settings.alerts.losses"
    static let settingsWindow1h: LocalizedStringKey = "settings.alerts.window.1h"
    static let settingsWindow6h: LocalizedStringKey = "settings.alerts.window.6h"
    static let settingsWindow24h: LocalizedStringKey = "settings.alerts.window.24h"
    static let settingsPriceTargets: LocalizedStringKey = "settings.alerts.priceTargets"
    static let settingsPriceAbove: LocalizedStringKey = "settings.alerts.priceAbove"
    static let settingsPriceBelow: LocalizedStringKey = "settings.alerts.priceBelow"
    static let settingsApprovalRequired: LocalizedStringKey = "settings.approvalRequired"
    static let settingsOpenLoginItems: LocalizedStringKey = "settings.openLoginItems"
    static let settingsAutoSaved: LocalizedStringKey = "settings.autoSaved"
    static let settingsSystem: LocalizedStringKey = "settings.system"
    static let settingsExport: LocalizedStringKey = "settings.export"
    static let settingsMarketAlertsExplanation: LocalizedStringKey =
        "settings.marketAlerts.explanation"
    static let settingsDataPrivacy: LocalizedStringKey = "settings.dataPrivacy"
    static let settingsLocalDataTitle: LocalizedStringKey = "settings.dataPrivacy.local.title"
    static let settingsLocalDataDetail: LocalizedStringKey = "settings.dataPrivacy.local.detail"
    static let settingsExportHistoryTitle: LocalizedStringKey =
        "settings.dataPrivacy.export.title"
    static let settingsExportHistoryDetail: LocalizedStringKey =
        "settings.dataPrivacy.export.detail"
    static let settingsExportSaved: LocalizedStringKey = "settings.dataPrivacy.export.saved"
    static let settingsClearHistory: LocalizedStringKey = "settings.dataPrivacy.clear.title"
    static let settingsClearHistoryDetail: LocalizedStringKey =
        "settings.dataPrivacy.clear.detail"
    static let settingsHistoryCleared: LocalizedStringKey = "settings.dataPrivacy.clear.cleared"
    static let settingsClearHistoryConfirmationTitle: LocalizedStringKey =
        "settings.dataPrivacy.clear.confirmation.title"
    static let settingsClearHistoryConfirmationMessage: LocalizedStringKey =
        "settings.dataPrivacy.clear.confirmation.message"
    static let settingsClearHistoryConfirm: LocalizedStringKey =
        "settings.dataPrivacy.clear.confirmation.action"
    static let settingsCancel: LocalizedStringKey = "settings.cancel"
    static let settingsAbout: LocalizedStringKey = "settings.about"
    static let settingsAboutSubtitle: LocalizedStringKey = "settings.about.subtitle"
    static let settingsDataSourcesTitle: LocalizedStringKey = "settings.about.dataSources.title"
    static let settingsDataSourcesDetail: LocalizedStringKey = "settings.about.dataSources.detail"
    static let settingsAboutLinksDetail: LocalizedStringKey = "settings.about.links.detail"
    static let settingsPrivacy: LocalizedStringKey = "settings.about.link.privacy"
    static let settingsLicense: LocalizedStringKey = "settings.about.link.license"
    static let settingsSupport: LocalizedStringKey = "settings.about.link.support"
    static let settingsOpensBrowser: LocalizedStringKey = "settings.about.link.hint"

    static let rhythmTitle: LocalizedStringKey = "rhythm.title"
    static let rhythmBuilding: LocalizedStringKey = "rhythm.building"
    static let rhythmBuildingDetail: LocalizedStringKey = "rhythm.buildingDetail"
    static let rhythmCoverage: LocalizedStringKey = "rhythm.coverage"
    static let rhythmLocalFootnote: LocalizedStringKey = "rhythm.localFootnote"
    static let rhythmAlertEnableHelp: LocalizedStringKey = "rhythm.alert.enableHelp"
    static let rhythmAlertDisableHelp: LocalizedStringKey = "rhythm.alert.disableHelp"
    static let accessibilityOn: LocalizedStringKey = "accessibility.on"
    static let accessibilityOff: LocalizedStringKey = "accessibility.off"

    static let welcomeEyebrow: LocalizedStringKey = "welcome.eyebrow"
    static let welcomeTitle: LocalizedStringKey = "welcome.title"
    static let welcomeSubtitle: LocalizedStringKey = "welcome.subtitle"
    static let welcomeRealmSignal: LocalizedStringKey = "welcome.signal.realm"
    static let welcomeMarketSignal: LocalizedStringKey = "welcome.signal.market"
    static let welcomeSignalsAccessibility: LocalizedStringKey = "welcome.signal.accessibility"
    static let welcomeHistoryTitle: LocalizedStringKey = "welcome.history.title"
    static let welcomeHistoryDetail: LocalizedStringKey = "welcome.history.detail"
    static let welcomeAlertsTitle: LocalizedStringKey = "welcome.alerts.title"
    static let welcomeAlertsDetail: LocalizedStringKey = "welcome.alerts.detail"
    static let welcomeDismiss: LocalizedStringKey = "welcome.dismiss"
    static let welcomeDismissHelp: LocalizedStringKey = "welcome.dismiss.help"
}
